import {bodyPoint} from './collisions.js?v=fleet-14';
export const ANCHOR_TUNING={payoutRateFtPerSec:3,workingPreloadFt:.45,stiffness:.012,damping:.0055,maxTension:.038,retrieveRateFtPerSec:1.35,retrieveMaxTension:.050,autoReleaseFt:2,maxLengthFt:300};
export function anchorBowX(sim){return Math.max(...sim.outline.map(p=>p[0]))-.6;}
export function anchorBowPoint(sim){return bodyPoint(sim.state,anchorBowX(sim),0,sim.scale);}
export function stowAnchor(sim){sim.anchor={mode:'stowed',target:null,lengthFt:0,tension:0,notice:''};}
export function anchorDown(sim){const a=sim.anchor;if(a.mode==='stowed'){const p=anchorBowPoint(sim);const inside=(p,shape)=>{const points=shape.points||[{x:shape.x,y:shape.y},{x:shape.x+shape.w,y:shape.y},{x:shape.x+shape.w,y:shape.y+shape.h},{x:shape.x,y:shape.y+shape.h}];let hit=false;for(let i=0,j=points.length-1;i<points.length;j=i++){const x=points[i],y=points[j];if((x.y>p.y)!==(y.y>p.y)&&p.x<(y.x-x.x)*(p.y-x.y)/(y.y-x.y)+x.x)hit=!hit;}return hit;};if(sim.solids.some(s=>inside(p,s))){a.notice='Move the bow over clear water before dropping the anchor.';return false;}a.target=p;a.lengthFt=0;a.tension=0;}a.mode='deployed';a.notice='';return true;}
export function anchorHold(sim){if(sim.anchor.mode!=='stowed')sim.anchor.mode='holding';}
export function anchorUp(sim){if(sim.anchor.mode!=='stowed')sim.anchor.mode='retrieving';}
export function applyAnchor(sim,dt,addForce){const a=sim.anchor;if(!a||a.mode==='stowed'||!a.target)return;const p=anchorBowPoint(sim),dx=a.target.x-p.x,dy=a.target.y-p.y,dist=Math.hypot(dx,dy),t=ANCHOR_TUNING;a.tension=0;if(a.mode==='retrieving'&&dist<=t.autoReleaseFt&&a.lengthFt<=t.autoReleaseFt){stowAnchor(sim);return;}if(a.mode==='deployed')a.lengthFt=Math.min(t.maxLengthFt,Math.max(a.lengthFt,Math.min(Math.max(0,dist-t.workingPreloadFt),a.lengthFt+t.payoutRateFtPerSec*dt)));if(a.mode==='retrieving')a.lengthFt=Math.max(0,a.lengthFt-t.retrieveRateFtPerSec*dt);if(dist<1e-5||dist<=a.lengthFt)return;const ux=dx/dist,uy=dy/dist,h=sim.state.a*Math.PI/180,r=anchorBowX(sim),w=sim.state.omega*Math.PI/180,vx=sim.state.vx*sim.scale-w*Math.sin(h)*r,vy=sim.state.vy*sim.scale+w*Math.cos(h)*r,outward=-(vx*ux+vy*uy);a.tension=Math.min(a.mode==='retrieving'?t.retrieveMaxTension:t.maxTension,Math.max(0,t.stiffness*(dist-a.lengthFt)+t.damping*Math.max(0,outward)));addForce(ux*a.tension,uy*a.tension,r/sim.boat.dimensions.lengthFt,0);}
