import {anchorDown,anchorHold,anchorUp} from '../simulation/anchor.js?v=anchor-scenery-21';
import {setOtherBoats} from '../simulation/traffic.js?v=anchor-scenery-21';
import {FLEET} from '../data/fleet.js?v=anchor-scenery-21';
import {bindDirectionDial} from './setup.js?v=touch-9';
import {SPAWNS} from '../data/marina.js?v=basin-slips-18';
import {resetSimulation,selectBoat} from '../simulation/state.js?v=anchor-scenery-21';
import {attachLine,LINE_DEFS,lineKey} from '../simulation/lines.js?v=fleet-14';
import {resetCamera} from '../graphics/camera.js?v=anchor-scenery-21';
export function bindControls(root,sim,camera){const q=s=>root.querySelector(s);const holds=new Map();let sequence=0;
 q('#spawn').replaceChildren(...Object.entries(SPAWNS).map(([key,p])=>{const o=document.createElement('option');o.value=key;o.textContent=p.label;if(key==='f')o.selected=true;return o;}));
 q('#boat-select').replaceChildren(...Object.values(FLEET).filter(entry=>!entry.npcOnly).map(entry=>{const o=document.createElement('option');o.value=entry.id;o.textContent=entry.name;return o;}));
 const windDial=bindDirectionDial(root,'wind'),currentDial=bindDirectionDial(root,'current');
 const buttons=[...root.querySelectorAll('.engine-button[data-engine]')];
 function applyHolds(){for(const side of ['port','stbd']){const active=[...holds.values()].filter(h=>h.engine===side||h.engine==='both').sort((a,b)=>b.order-a.order)[0];sim.state[side]=active?active.power:0;}if(sim.boat.propulsion.type==='singleOutboard')sim.state.stbd=0;const thruster=[...holds.values()].filter(h=>h.engine==='thruster').sort((a,b)=>b.order-a.order)[0];sim.state.bowThruster=sim.boat.propulsion.bowThruster&&thruster?thruster.power:0;for(const button of buttons){const held=[...holds.values()].some(h=>h.button===button);button.classList.toggle('held',held);button.setAttribute('aria-pressed',String(held));}update();}
 function begin(token,button){holds.set(token,{button,engine:button.dataset.engine,power:+button.dataset.power/100,order:++sequence});applyHolds();}
 function end(token){if(holds.delete(token))applyHolds();}
 const neutral=()=>{holds.clear();applyHolds();};
 for(const button of buttons){button.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'&&e.button!==0)return;e.preventDefault();button.setPointerCapture(e.pointerId);begin('pointer:'+e.pointerId,button);});for(const name of ['pointerup','pointercancel','lostpointercapture'])button.addEventListener(name,e=>end('pointer:'+e.pointerId));button.addEventListener('keydown',e=>{if(e.code==='Space'||e.code==='Enter'){e.preventDefault();if(!e.repeat)begin('key:'+button.dataset.engine+button.dataset.power,button);}});button.addEventListener('keyup',e=>{if(e.code==='Space'||e.code==='Enter'){e.preventDefault();end('key:'+button.dataset.engine+button.dataset.power);}});button.addEventListener('blur',()=>end('key:'+button.dataset.engine+button.dataset.power));button.addEventListener('contextmenu',e=>e.preventDefault());}
 for(const name of ['pointerup','pointercancel'])window.addEventListener(name,e=>end('pointer:'+e.pointerId));
 function update(){const anchor=sim.anchor;q('#anchor-status').textContent=anchor.notice||({stowed:'Stowed',deployed:'Paying out',holding:'Holding rode',retrieving:'Retrieving'}[anchor.mode]+(anchor.target?' · '+anchor.lengthFt.toFixed(1)+' ft · '+(anchor.tension>.002?'Taut':'Slack'):''));for(const [id,mode] of [['down','deployed'],['hold','holding'],['up','retrieving']]){q('#anchor-'+id).setAttribute('aria-pressed',String(anchor.mode===mode));q('#anchor-'+id).disabled=id!=='down'&&anchor.mode==='stowed';}q('#other-boats-note').textContent=(sim.otherBoats?.length||0)+' parked boats · starting area kept clear';const s=sim.state;for(const [key,id] of [['port','pv'],['stbd','sv']])q('#'+id).textContent=s[key]===0?'N':(s[key]>0?'Ahead ':'Reverse ')+Math.round(Math.abs(s[key])*100)+'%';q('#bv').textContent=s.port===s.stbd?(s.port===0?'N':(s.port>0?'Ahead ':'Reverse ')+Math.round(Math.abs(s.port)*100)+'%'):'Mixed';q('#av').textContent=s.steer+'°';q('#av-scene').textContent=s.steer+'°';q('#steer-scene').value=s.steer;for(const side of ['port','stbd'])q('#overlay-'+side).textContent=s[side]===0?'N':(s[side]>0?'FWD ':'REV ')+Math.round(Math.abs(s[side])*100)+'%';q('#helm-height').value=camera.helmHeightOffset??0;q('#helm-height-value').textContent='+'+(camera.helmHeightOffset??0).toFixed(2)+' ft';q('#helm-height-note').textContent='Helm eye height: '+((sim.helm?.height??6.262)+(camera.helmHeightOffset??0)).toFixed(1)+' ft above water. Applies in Helm view.';q('#cv').textContent=(camera.catchup??3)+' s';q('#view').textContent='View · '+({far:'Far',medium:'Medium',helm:'Helm'}[camera.mode]);q('#catchup-note').textContent=camera.mode==='helm'?'Helm stays aligned with the boat':'Far / Medium follow delay · 0 = immediate';q('#wv').textContent=sim.environment.wind+' kt';q('#uv').textContent=sim.environment.current.toFixed(1)+' kt';const degrees=sim.environment.windDirection,directions=['N','NE','E','SE','S','SW','W','NW'];q('#dv').textContent=directions[Math.round(degrees/45)%8]+' · '+degrees+'°';q('#ud').textContent=directions[Math.round(sim.environment.currentDirection/45)%8]+' · '+sim.environment.currentDirection+'°';q('#environment-status').textContent='Wind '+sim.environment.wind+' kt · Current '+sim.environment.current.toFixed(1)+' kt';windDial.update();currentDial.update();q('.scene-hint').textContent=camera.mode==='helm'?'Drag to look · Recenter to face forward':'Drag to look · release to return';q('#wind-arrow').textContent='Wind → '+directions[Math.round(degrees/45)%8]+' · waves travel downwind';q('#readout').textContent=(Math.hypot(s.vx,s.vy)*110).toFixed(1)+' kt';
 for(const side of ['port','stbd'])for(const type of Object.keys(LINE_DEFS)){const line=sim.lines[lineKey(type,side)],button=q('#line-'+side+'-'+type),status=line?(line.tension>.0005?'Taut':'Slack'):'Released';button.setAttribute('aria-pressed',String(!!line));button.dataset.state=status.toLowerCase();button.querySelector('small').textContent=status;}
 for(const side of ['port','stbd']){const b=q('#fender-'+side);b.setAttribute('aria-pressed',String(sim.fenders[side]));b.querySelector('small').textContent=sim.fenders[side]?'Deployed':'Stowed';}
 }
 function sync(){sim.state.steer=+q('#steer').value;sim.environment.wind=+q('#wind').value;sim.environment.windDirection=+q('#wind-direction').value;sim.environment.current=+q('#current').value;sim.environment.currentDirection=+q('#current-direction').value;update();}
 for(const key of ['steer','wind','wind-direction','current','current-direction'])q('#'+key).oninput=sync;
 q('#anchor-down').onclick=()=>{anchorDown(sim);update();};q('#anchor-hold').onclick=()=>{anchorHold(sim);update();};q('#anchor-up').onclick=()=>{anchorUp(sim);update();};
 q('#setup-open').onclick=()=>{neutral();q('#setup-screen').showModal();};q('#setup-close').onclick=()=>q('#setup-screen').close();
 q('#steer-scene').oninput=()=>{q('#steer').value=q('#steer-scene').value;sync();};
 const orientation=matchMedia('(orientation: landscape)');let landscape=orientation.matches;const checkOrientation=()=>{if(orientation.matches!==landscape){landscape=orientation.matches;neutral();}};orientation.addEventListener('change',checkOrientation);const anchorTools=q('.anchor-tools');function placeAnchorControls(){q(orientation.matches?'#anchor-landscape':'#anchor-portrait').append(anchorTools);}orientation.addEventListener('change',placeAnchorControls);placeAnchorControls();window.addEventListener('resize',checkOrientation);window.addEventListener('orientationchange',neutral);
 q('#helm-height').oninput=()=>{camera.helmHeightOffset=+q('#helm-height').value;update();};
 q('#catchup').oninput=()=>{camera.catchup=+q('#catchup').value;update();};
 q('#view').onclick=()=>{const modes=['far','medium','helm'];camera.mode=modes[(modes.indexOf(camera.mode)+1)%3];resetCamera(camera,sim.state,sim.scale);update();};
 q('#recenter').onclick=()=>{resetCamera(camera,sim.state,sim.scale);update();};
 q('#map-toggle').onclick=()=>{const b=q('#map-toggle'),expanded=b.classList.toggle('expanded');b.setAttribute('aria-expanded',String(expanded));};
 for(const b of root.querySelectorAll('[data-steer]'))b.onclick=()=>{q('#steer').value=b.dataset.steer;sync();};
 function reset(){neutral();resetSimulation(sim,q('#spawn').value);resetCamera(camera,sim.state,sim.scale);q('#steer').value=0;update();}
 function updateBoatControls(){q('header strong').textContent='Docking Trainer · '+sim.model.definition.name;const single=sim.boat.propulsion.type==='singleOutboard';for(const column of root.querySelectorAll('.engine-column')){const engine=column.querySelector('[data-engine]')?.dataset.engine;column.style.display=single&&engine!=='port'?'none':'';}q('.engine-controls').style.gridTemplateColumns=single?'1fr':'';q('.scene-throttle.stbd').style.display=single?'none':'';q('.engine-column .column-title').firstChild.nodeValue=single?'ENGINE ':'PORT ';q('.scene-throttle.port strong').firstChild.nodeValue=single?'ENGINE':'PORT';for(const button of root.querySelectorAll('[data-engine=port]'))button.setAttribute('aria-label',(single?'Engine':'Port engine')+' '+Math.abs(+button.dataset.power)+' percent '+(+button.dataset.power>0?'ahead':'reverse')+', hold for power');for(const el of root.querySelectorAll('[data-thruster-controls]'))el.hidden=!sim.boat.propulsion.bowThruster;q('#boat-note').textContent=single?'21-foot bowrider · one steerable outboard':sim.model.id==='Express-33'?'33.5 feet overall · existing twin-sterndrive handling':sim.model.id==='sportfisher-30'?'30-foot hull · old 30-foot twin-inboard handling':'60-foot motor yacht · twin inboards · bow thruster';}
 q('#other-boats').value=sim.otherBoatsDensity||'none';
 q('#other-boats').onchange=()=>{const density=q('#other-boats').value;neutral();setOtherBoats(sim,density);update();};
 q('#boat-select').onchange=()=>{neutral();selectBoat(sim,q('#boat-select').value,q('#spawn').value);resetCamera(camera,sim.state,sim.scale);q('#steer').value=0;updateBoatControls();update();};updateBoatControls();
 q('#reset').onclick=reset;q('#spawn').onchange=reset;
 for(const side of ['port','stbd'])for(const type of Object.keys(LINE_DEFS))q('#line-'+side+'-'+type).onclick=()=>{const notice=attachLine(sim,type,side);const button=q('#line-'+side+'-'+type);button.title=notice;update();};
 for(const side of ['port','stbd'])q('#fender-'+side).onclick=()=>{sim.fenders[side]=!sim.fenders[side];update();};
 // Switching tabs always puts both engines into neutral.

 window.addEventListener('blur',neutral);document.addEventListener('visibilitychange',()=>{if(document.hidden)neutral();});
 update();return {update,reset};
}


