import {DOCKS,DOCK_POLYGONS,LAND,BOUNDS} from '../data/marina.js?v=basin-slips-18';
export function createMiniMap(svg,sim){const size=220,span=Math.max(BOUNDS.maxX-BOUNDS.minX,BOUNDS.maxY-BOUNDS.minY),scale=(size-14)/span,ox=(size-(BOUNDS.maxX-BOUNDS.minX)*scale)/2,oy=(size-(BOUNDS.maxY-BOUNDS.minY)*scale)/2,point=p=>[ox+(p.x-BOUNDS.minX)*scale,oy+(p.y-BOUNDS.minY)*scale];const ns='http://www.w3.org/2000/svg';const node=(type,attrs)=>{const n=document.createElementNS(ns,type);for(const [k,v] of Object.entries(attrs))n.setAttribute(k,v);svg.append(n);return n;};svg.replaceChildren();node('rect',{width:size,height:size,fill:'#234957'});
 for(const p of LAND)node('polygon',{points:p.points.map(point).map(p=>p.join(',')).join(' '),fill:'#6b805a'});
 for(const d of DOCKS){const [x,y]=point(d);node('rect',{x,y,width:Math.max(.7,d.w*scale),height:Math.max(.7,d.h*scale),fill:'#c0a37a'});}
 for(const p of DOCK_POLYGONS)node('polygon',{points:p.points.map(point).map(p=>p.join(',')).join(' '),fill:p.kind==='stone'?'#92988d':'#b9b19a'});
 const anchorLine=node('line',{stroke:'#f0d69e','stroke-width':1}),anchorPoint=node('circle',{r:2,fill:'#eda850'});
 const traffic=node('g',{});let revision=-1;
 const boat=node('path',{id:'map-boat',d:'M10 0 L-6 -5 L-3 0 L-6 5 Z',fill:'#fff4a3',stroke:'#102333','stroke-width':1.5});let last=-Infinity;function paint(now=0){if(now-last<100)return;last=now;const target=sim.anchor?.target;anchorLine.setAttribute('visibility',target?'visible':'hidden');anchorPoint.setAttribute('visibility',target?'visible':'hidden');if(target){const [ax,ay]=point(target),[bx,by]=point({x:sim.state.x*sim.scale,y:sim.state.y*sim.scale});for(const [k,v] of Object.entries({x1:bx,y1:by,x2:ax,y2:ay}))anchorLine.setAttribute(k,v);anchorPoint.setAttribute('cx',ax);anchorPoint.setAttribute('cy',ay);}if(revision!==sim.trafficRevision){traffic.replaceChildren();for(const b of sim.otherBoats||[]){const n=document.createElementNS(ns,'polygon');n.setAttribute('points',b.points.map(point).map(p=>p.join(',')).join(' '));n.setAttribute('fill','#d9e4e8');traffic.append(n);}revision=sim.trafficRevision;}const [x,y]=point({x:sim.state.x*sim.scale,y:sim.state.y*sim.scale});boat.setAttribute('transform',`translate(${x} ${y}) rotate(${sim.state.a})`);}paint();return {paint};
}
