// Keep independent pointers; never treat a second finger as a pinch in play areas.
export function bindGameTouch(root){const regions='.scene-frame,.helm-panel';let lastTouchButton=null,lastTouchAt=0;const belongs=e=>e.target.closest?.(regions);const block=e=>{if(belongs(e)&&e.cancelable)e.preventDefault();};
 for(const type of ['touchstart','touchmove','gesturestart','gesturechange','gestureend'])root.addEventListener(type,block,{passive:false});
 // Touchstart cancellation suppresses compatibility clicks in Safari. Execute
 // discrete button actions on pointerdown, while engine holds retain their IDs.
 root.addEventListener('pointerdown',e=>{const b=e.target.closest?.('button');if(e.pointerType==='touch'&&b&&belongs(e)&&!b.classList.contains('engine-button')){e.preventDefault();lastTouchButton=b;lastTouchAt=performance.now();b.click();}});
 root.addEventListener('click',e=>{if(e.isTrusted&&e.target.closest?.('button')===lastTouchButton&&performance.now()-lastTouchAt<800){e.preventDefault();e.stopImmediatePropagation();}},true);
}

export function bindTouchRanges(root){for(const input of root.querySelectorAll('input[type=range]')){let pointer=null;const change=e=>{const r=input.getBoundingClientRect(),min=+input.min,max=+input.max,step=+input.step||1,pad=Math.min(10,r.width/4),t=Math.max(0,Math.min(1,(e.clientX-r.left-pad)/(r.width-2*pad)));input.value=Math.max(min,Math.min(max,min+Math.round(t*(max-min)/step)*step));input.dispatchEvent(new Event('input',{bubbles:true}));};input.addEventListener('pointerdown',e=>{if(e.pointerType!=='touch'||pointer!==null)return;e.preventDefault();pointer=e.pointerId;input.setPointerCapture(pointer);change(e);});input.addEventListener('pointermove',e=>{if(e.pointerId===pointer){e.preventDefault();change(e);}});for(const type of ['pointerup','pointercancel','lostpointercapture'])input.addEventListener(type,e=>{if(e.pointerId===pointer)pointer=null;});}}
export function bindScrollGrip(grip){let pointer=null,lastY=0;grip.addEventListener('pointerdown',e=>{if(pointer!==null||(e.pointerType==='mouse'&&e.button!==0))return;e.preventDefault();pointer=e.pointerId;lastY=e.clientY;grip.setPointerCapture(pointer);grip.classList.add('scrolling');});grip.addEventListener('pointermove',e=>{if(e.pointerId!==pointer)return;e.preventDefault();window.scrollBy(0,lastY-e.clientY);lastY=e.clientY;});for(const type of ['pointerup','pointercancel','lostpointercapture'])grip.addEventListener(type,e=>{if(e.pointerId===pointer){pointer=null;grip.classList.remove('scrolling');}});grip.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','PageUp','PageDown'].includes(e.key)){e.preventDefault();window.scrollBy(0,(e.key.endsWith('Up')?-1:1)*(e.key.startsWith('Page')?innerHeight*.7:80));}});}
