import {buildBoat} from '../data/boat-generator.js?v=anchor-scenery-21';
import * as THREE from '../../vendor/three.module.js?v=touch-9';
import {createCruiser} from './boats.js?v=workboat-28';
import {npcShape} from '../simulation/traffic.js?v=workboat-28';
// Shared geometry and GPU instances keep a crowded marina inexpensive. Full
// cosmetics appear nearby; distant boats use their matching hull silhouette.
function bakedParts(vessel){vessel.updateMatrixWorld(true);const groups=new Map();vessel.traverse(o=>{if(!o.isMesh)return;const key=o.material.uuid;if(!groups.has(key))groups.set(key,{material:o.material,positions:[],normals:[]});const part=groups.get(key),g=(o.geometry.index?o.geometry.toNonIndexed():o.geometry.clone());g.applyMatrix4(o.matrixWorld);part.positions.push(...g.attributes.position.array);part.normals.push(...g.attributes.normal.array);g.dispose();});const parts=[...groups.values()].map(p=>{const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(p.positions,3));geometry.setAttribute('normal',new THREE.Float32BufferAttribute(p.normals,3));return {geometry,material:p.material};});const geometries=new Set();vessel.traverse(o=>{if(o.geometry)geometries.add(o.geometry);});for(const g of geometries)g.dispose();return parts;}
function distantBoat(entry){if(entry.id==='Motoryacht-60'||entry.npcOnly)return createCruiser({...entry,model:buildBoat({...entry.p,panelSteps:1})},false); const group=new THREE.Group(),colors=entry.definition.colors,p=entry.p,poly=entry.outline;const material=color=>new THREE.MeshStandardMaterial({color,roughness:.65,side:THREE.DoubleSide});const white=material(colors.upperHull),deck=material(colors.deck),cabin=material(colors.superstructure),glass=material(colors.windows);const vertices=[],n=poly.length;for(let i=0;i<n;i++){const a=poly[i],b=poly[(i+1)%n];vertices.push(a[0],2.4,a[1],b[0],2.4,b[1],a[0]*.8,-.5,a[1]*.8,b[0],2.4,b[1],b[0]*.8,-.5,b[1]*.8,a[0]*.8,-.5,a[1]*.8);}const hull=new THREE.BufferGeometry();hull.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));hull.computeVertexNormals();group.add(new THREE.Mesh(hull,white));const shape=new THREE.Shape();poly.forEach(([x,z],i)=>i?shape.lineTo(x,-z):shape.moveTo(x,-z));shape.closePath();const top=new THREE.ShapeGeometry(shape);top.rotateX(-Math.PI/2);top.translate(0,2.4,0);group.add(new THREE.Mesh(top,deck));const box=(x,y,z,w,h,d,mat)=>{const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);m.position.set(x,y,z);group.add(m);};const x=p.enclosureOffset+p.enclosureLength/2-p.aft-entry.originShift,w=p.enclosureLength*.65,d=p.beam*p.enclosureWidth/100,h=p.cabinHeight+p.enclosureHeight;if(entry.id==='bowrider'){box(x+w/2,3,0,.3,1.4,d,glass);box(-p.aft-entry.originShift-1.2,1.3,0,2,2,1.4,material('#343b40'));}else{box(x,2.4+h*.35,0,w,h*.7,d,cabin);box(x,2.4+h*.8,0,w,h*.25,d*.96,glass);box(x,2.4+h,0,w+.7,.3,d+.5,cabin);}return group;}
export function createOtherBoatGraphics(scene,sim){const group=new THREE.Group();scene.add(group);const templates=new Map();let revision=-1,lastX=Infinity,lastY=Infinity;function rebuild(){for(const child of [...group.children]){child.removeFromParent();child.dispose();}const x=sim.state.x*sim.scale,y=sim.state.y*sim.scale,batches=new Map();for(const boat of sim.otherBoats||[]){const detail=Math.hypot(boat.xCenter-x,boat.yCenter-y)<220,key=boat.boatKey+':'+detail;if(!batches.has(key))batches.set(key,{boats:[],shape:npcShape(boat.boatKey),detail});batches.get(key).boats.push(boat);}for(const [key,batch] of batches){if(!templates.has(key))templates.set(key,bakedParts(batch.detail?createCruiser(batch.shape.entry):distantBoat(batch.shape.entry)));const {cx,cy,sx,sz}=batch.shape;const matrix=new THREE.Matrix4(),rotation=new THREE.Matrix4(),scale=new THREE.Matrix4().makeScale(sx,1,sz),center=new THREE.Matrix4().makeTranslation(-cx,0,-cy);for(const part of templates.get(key)){const mesh=new THREE.InstancedMesh(part.geometry,part.material,batch.boats.length);batch.boats.forEach((b,i)=>{matrix.makeTranslation(b.xCenter,0,b.yCenter);rotation.makeRotationY(-b.heading*Math.PI/180);matrix.multiply(rotation).multiply(scale).multiply(center);mesh.setMatrixAt(i,matrix);});mesh.instanceMatrix.needsUpdate=true;mesh.computeBoundingSphere();mesh.receiveShadow=false;mesh.castShadow=false;group.add(mesh);}}revision=sim.trafficRevision;lastX=x;lastY=y;}
return {update(){if(revision!==sim.trafficRevision||Math.hypot(sim.state.x*sim.scale-lastX,sim.state.y*sim.scale-lastY)>25)rebuild();}};
}
// One scripted departure boat; parked-boat instances remain unchanged.
export function createMovingBoatGraphics(scene,sim){const group=new THREE.Group();scene.add(group);let revision=-1;const models=new Map();return {update(){if(revision!==sim.levelRevision){group.traverse(o=>{o.geometry?.dispose();if(o.material)o.material.dispose();});group.clear();models.clear();revision=sim.levelRevision;}for(const b of sim.movingBoats||[]){if(!models.has(b.id)){const shape=npcShape(b.boatKey),vessel=createCruiser(shape.entry),wrapper=new THREE.Group();vessel.position.set(-shape.cx,0,-shape.cy);wrapper.add(vessel);wrapper.scale.set(shape.sx,1,shape.sz);group.add(wrapper);models.set(b.id,wrapper);}const model=models.get(b.id);model.visible=!b.finished;model.position.set(b.xCenter,0,b.yCenter);model.rotation.y=-b.heading*Math.PI/180;}}};}
